# Generated by Django 5.0.2 on 2024-02-24 13:00

import django.core.validators
import django.db.models.deletion
import django.db.models.query
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "age",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(12)]
                    ),
                ),
                ("password", models.CharField(max_length=30)),
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                ("last_name", models.CharField(blank=True, max_length=30, null=True)),
                ("profile_picture", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Месо", "Месо"),
                            ("Риба", "Риба"),
                            ("Млечни продукти", "Млечни продукти"),
                            ("Зърнени храни", "Зърнени храни"),
                            ("Плодове и зеленчуци", "Плодове и зеленчуци"),
                            ("Добавки/Сосове", "Добавки/Сосове"),
                            ("Други", "Други"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "utility",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.1),
                            django.core.validators.MaxValueValidator(5.0),
                        ]
                    ),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("image_url", models.URLField()),
                ("summary", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        default=django.db.models.query.QuerySet.first,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="games",
                        to="blog.profile",
                    ),
                ),
            ],
        ),
    ]
